
services:
    # phpmyadmin:
    #     image: phpmyadmin:latest
    #     restart: always
    #     ports:
    #         - 8013:80
    #     environment:
    #         PMA_HOST: mysql
    #     networks:
    #         - my_network
    mysql:
        image: mysql:latest
        restart: on-failure
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        ports:
            - "3307:3306"
        volumes:
            - ./mysql-data:/var/lib/mysql
            - ./init-db.sql:/docker-entrypoint-initdb.d/init.sql
        # command: >
        #     sh -c 'exec mysqld --init-file=/docker-entrypoint-initdb.d/init.sql'
        networks:
            - my_network
    api:
        build: ghcr.io/pablosr06/macaronesiaanalyser:main
        restart: always
        ports:
            - "5000:8080"
        volumes:
            - .:/app
        command: python /app/app.py
        env_file:
            - .env
        depends_on:
            - mysql
        networks:
            - my_network

networks:
  my_network:
    driver: bridge
