services:
    mysql:
        image: mysql:latest
        restart: on-failure
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        ports:
            - "3307:3306"
        volumes:
            - ./mysql-data:/var/lib/mysql
            - ./init-db.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - my_network
    api:
        image: ghcr.io/pablosr06/macaronesiaanalyser:main
        restart: always
        ports:
            - "5000:8080"
        env_file:
            - .env
        depends_on:
            - mysql
        networks:
            - my_network

networks:
  my_network:
    driver: bridge
